spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TimeVenture?serverTimezone=UTC
    username: TimeVenture
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:

            redirect-url: "http://localhost:91/login/oauth2/code/google"
            scope: email, profile
  redis:
    host: localhost
    port: 6379
    password: ""